### PR TITLE
Add exchange info retrieval

### PR DESCRIPTION
**Pull request by dionbosschieter**
You want to be able to get the exchange info, so you can make sure your order requests pass the binance filters.

### CODE REVIEW

**Comment by Tyrion85** [comment]
What's the logic behind placing the GetExchangeInfo() func in `account.go`? Wouldn't a better place for it be in `market.go`, or in completely separate file - considering that GetExchangeInfo() is an unsigned Endpoint, and not related to account info in particular..?

In general, +1 for this feature. Ran into the issue with filters this morning - for example, each coin pair has it's own set of rules regarding quantity, min/max price, etc, that should be followed when placing Orders. And as far as I can see, ExchangeInfo Endpoint is the only way to get those rules via API.

**Comment by matthewwoop** [comment]
Agree with @Tyrion85 - Great feature addition, I wasn't even aware of it. Doesn't seem to be mentioned in their [documentation](https://www.binance.com/restapipub.html)

Definitely makes more sense in `market.go`. 

Happy to merge once code is in the appropriate place, @dionbosschieter

**Comment by Tyrion85** [comment]
Yeah, there is no mention of it in official documentation. Seems like Binance has the (usual) problem with mismatch between docs and implementation. I've found that this github repo is more up-to-date: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

**Comment by dionbosschieter** [comment]
I just pushed a new version so `GetExchangeInfo` is part of `market.go`

**Comment by matthewwoop** [comment]
@dionbosschieter Awesome, last piece is to move the type definitions into `market_requests.go` and `market_response.go`

**Comment by dionbosschieter** [comment]
Done

**Pull request merged**
