### PR TITLE
GetAllOrders method + go fmt 

### PR DESCRIPTION
**Pull request by kustov-an**
Implementation of `api/v3/allOrders` request.
Also formatted the code using `go fmt`.

### CODE REVIEW

**Comment by scottjbarr** [comment]
Please merge this. On so many occassions I've been looking at code in this package and as soon as I save it, the entire file changes. The majority of Go developers seem to have goimports run on save, from my experience with teams and other developers.

**Comment by scottjbarr** [comment]
@kustov-an maybe it is worth submitting a PR with just the formatting first?

**Comment by scottjbarr** [comment]
@kustov-an #15 was just merged, which contained the formatting in one commit. Could you pick out the `GetAllOrders` pieces?

**Comment by pdepip** [comment]
Closing as it was merged in PR #16 thanks to @scottjbarr

**Pull request closed without merging**
